In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
#import complete_transformer as ct
import joblib as jb

In [2]:
df_new = pd.read_excel('KPMG_VI_New_raw_data.xlsx', sheet_name='NewCustomerList')
df_new.head()

,customer_id,first_name,last_name,gender,past_3_years_bike_related_purchases,DOB,job_title,job_industry_category,wealth_segment,deceased_indicator,owns_car,tenure,address,postcode,state,country,property_valuation
0,1,Chickie,Brister,Male,86,1957-07-12,General Manager,Manufacturing,Mass Customer,N,Yes,14,45 Shopko Center,4500,QLD,Australia,6
1,2,Morly,Genery,Male,69,1970-03-22,Structural Engineer,Property,Mass Customer,N,No,16,14 Mccormick Park,2113,NSW,Australia,11
2,3,Ardelis,Forrester,Female,10,1974-08-28,Senior Cost Accountant,Financial Services,Affluent Customer,N,No,10,5 Colorado Crossing,3505,VIC,Australia,5
3,4,Lucine,Stutt,Female,64,1979-01-28,Account Representative III,Manufacturing,Affluent Customer,N,Yes,5,207 Annamark Plaza,4814,QLD,Australia,1
4,5,Melinda,Hadlee,Female,34,1965-09-21,Financial Analyst,Financial Services,Affluent Customer,N,No,19,115 Montana Place,2093,NSW,Australia,9

In [3]:
df_new.replace({0 : np.nan}, inplace=True)

In [4]:
set(df_new.tenure)

{nan,
 1.0,
 2.0,
 3.0,
 4.0,
 5.0,
 6.0,
 7.0,
 8.0,
 9.0,
 10.0,
 11.0,
 12.0,
 13.0,
 14.0,
 15.0,
 16.0,
 17.0,
 18.0,
 19.0,
 20.0,
 21.0,
 22.0,
 nan}

In [5]:
#df_new.to_csv('new_customers.csv', index=False)

In [6]:
data_tidying, data_transformer, model = jb.load('sprocket_model.sav')

In [7]:
from prediction_pipeline import prediction_pipeline

In [8]:
new_predictions = prediction_pipeline(df_new, data_tidying, data_transformer, model)
print(new_predictions)

[2725.51680461 2706.97857908 2680.11462105 2709.09706551 2693.73583895
 2703.1959339  2703.77982654 2705.6507076  2711.89507212 2721.72278033
 2719.13330908 2696.20462244 2707.09031614 2687.24054746 2685.71085342
 2716.41346038 2708.60051721 2701.96803652 2703.63583197 2682.10434613
 2709.26315338 2720.16989957 2704.61490557 2694.90110759 2697.76338575
 2697.11388649 2695.31376211 2707.82189409 2702.51206929 2687.39816946
 2709.27763864 2718.15247122 2718.0954413  2712.84889409 2690.2849381
 2716.74630665 2712.13590294 2700.87480803 2711.50015146 2718.91441052
 2689.44176849 2690.22534882 2696.37382482 2689.95677341 2703.15351894
 2694.77798831 2705.00072508 2715.91563684 2707.77242272 2694.16460531
 2697.22687902 2723.70747251 2714.18854801 2702.07067882 2698.70816644
 2693.20076861 2708.60252549 2689.51272841 2711.76175134 2675.14979214
 2720.08696169 2710.41993404 2708.91324023 2711.30207062 2703.7348313
 2693.75031067 2709.54000299 2708.69612202 2726.07495278 2714.85835737
 2699.68955306 2705.03805306 2708.43593205 2693.97805459 2712.82347169
 2720.70051527 2702.69293699 2699.24972408 2698.81882431 2685.32342543
 2705.97733882 2691.56079752 2688.09385726 2702.76479511 2713.27558666
 2685.14965959 2682.66373038 2695.3801979  2712.70158654 2701.92006508
 2714.15952092 2689.20879007 2699.63249256 2724.20559944 2701.91062117
 2725.00927371 2702.28353461 2711.92546856 2698.67099468 2695.69588795
 2704.72124043 2700.02958552 2694.57033966 2697.9140787  2707.09124576
 2716.9236801  2682.40839115 2691.14039278 2699.45943594 2694.32746278
 2709.92048434 2716.55165465 2707.54246404 2687.77501191 2694.6729577
 2699.46468503 2715.56502203 2699.86751209 2714.24529228 2691.52083944
 2703.91748227 2706.95946327 2697.3071411  2689.36734079 2712.71000158
 2715.11637541 2692.54969093 2708.16928141 2694.83616729 2701.81873528
 2705.13971153 2711.87987569 2697.96012516 2700.22711925 2696.33515973
 2711.75212477 2700.85228628 2709.50518174 2702.41530168 2699.99203664
 2720.03070611 2708.98955313 2710.13845346 2710.91098083 2688.45913967
 2693.9262811  2696.18248947 2700.97599579 2691.2272733  2687.0088409
 2706.28491518 2695.75337675 2719.02510803 2698.53573387 2700.48555029
 2706.73095623 2710.15525874 2684.62060079 2690.84574814 2693.38789465
 2698.73670543 2692.04885213 2704.44458145 2726.93536682 2693.54388102
 2702.37781662 2702.34167788 2709.26233927 2698.16262414 2701.55620803
 2689.24892219 2705.82845355 2721.03696205 2715.78345532 2687.37431992
 2695.09100048 2703.80891744 2702.49320602 2724.98225389 2703.72159476
 2700.90084077 2710.81659028 2707.5127996  2714.51841928 2690.84767161
 2716.21627764 2692.48422589 2704.37481467 2687.62711549 2706.46002409
 2689.21112236 2711.61731182 2678.68898811 2691.98264277 2693.04057133
 2691.26687128 2699.65755465 2696.78073138 2704.15190865 2708.9459372
 2716.81506435 2696.17470661 2711.92546998 2706.24570869 2695.48626418
 2693.84071799 2704.09660331 2705.89680953 2683.1657333  2719.04725241
 2705.02754817 2717.22070842 2695.13626559 2691.77907048 2696.03834065
 2694.85257252 2691.33697471 2694.19053894 2723.37729594 2694.07566502
 2713.88703475 2719.02305276 2691.22805409 2706.8873065  2718.004307
 2718.1589394  2700.11133322 2709.43154249 2693.98222373 2705.94019081
 2715.32666489 2709.40988681 2712.44530345 2690.12709245 2697.68759711
 2697.36400836 2711.78888328 2696.36061931 2713.17124833 2703.37182015
 2693.4992843  2701.95558631 2712.89802061 2701.47041551 2692.96662165
 2688.23613327 2706.28653322 2719.74619092 2716.22040088 2706.61489543
 2706.2028368  2725.20957569 2683.58942337 2701.31557857 2705.94480623
 2680.02445317 2688.16650316 2701.98028733 2708.40628589 2690.17924023
 2691.25387249 2691.95662357 2723.97532426 2706.10068068 2722.2090041
 2686.97956768 2703.45003761 2702.23088023 2714.34396726 2698.15062982
 2722.05393086 2715.51535002 2702.7097188  2702.1485624  2704.10013944
 2708.93465146 2694.98357602 2708.34566765 2708.75065575 2700.76433844
 2694.39785323 2688.79318263 2686.65079437 2713.38008844 2703.85051167
 2709.20472923 2711.29598798 2685.15779776 2712.85072717 2710.1712774
 2703.54909982 2691.35029211 2708.51923353 2707.40833738 2706.04427559
 2710.69797205 2705.64313494 2724.45882909 2695.92797251 2692.24710197
 2711.0134294  2706.80464175 2721.20773732 2691.75993118 2710.64411678
 2708.333537   2702.91147345 2707.36948103 2692.19051376 2708.77998122
 2694.54662768 2679.21021254 2705.74044424 2713.55552731 2711.07927639
 2696.38302542 2689.59835393 2701.05524942 2704.56136539 2725.67509465
 2718.49128525 2705.63279091 2691.97366874 2699.14859166 2704.61733244
 2682.46398717 2701.10013393 2714.57973548 2704.9080702  2687.78585066
 2703.00326616 2712.71326084 2714.87418861 2708.15088411 2708.95845459
 2708.83534719 2698.6353562  2699.61152066 2703.61953512 2707.27083961
 2716.01943269 2697.26968923 2709.90225405 2698.77248241 2714.32855264
 2704.40441046 2699.34281218 2717.82177786 2681.25778425 2706.4041309
 2697.767599   2702.62609532 2703.11573876 2705.76601661 2701.7087631
 2685.48870429 2693.88016861 2706.84906909 2694.96941017 2708.443157
 2704.83094018 2696.50441305 2709.3662685  2700.74505312 2712.80668818
 2707.53724759 2702.48334511 2709.45278671 2692.60578012 2699.77429593
 2698.12753214 2709.63992604 2694.19573678 2707.37867331 2700.39760393
 2706.51446714 2705.69376735 2703.50335454 2686.54600751 2705.82616267
 2684.2542554  2700.41873677 2721.25565231 2693.29270715 2725.91087274
 2716.4480006  2684.24957983 2690.40654899 2707.12804897 2695.6767547
 2685.01323154 2694.60720684 2712.25333008 2696.36151353 2715.37863175
 2706.954089   2710.03853659 2710.96226545 2711.00593305 2711.27593008
 2703.55421732 2717.03156168 2714.94542762 2726.65732137 2703.99814181
 2702.74341526 2695.19853619 2686.87843315 2691.33774749 2680.72141371
 2705.38928837 2709.64744917 2703.39928227 2690.72210887 2698.55692533
 2719.04734035 2701.19328782 2698.85768153 2728.80750756 2696.62127365
 2699.57234565 2718.03052019 2695.94441953 2707.7428462  2716.75315437
 2702.90697268 2709.77670962 2695.60060211 2693.45549256 2690.06906231
 2704.11417608 2704.80328937 2711.34846738 2702.18034353 2688.36690676
 2704.36730345 2707.36067769 2706.9273077  2707.79361801 2709.90776565
 2703.83270761 2698.79525653 2699.43034634 2693.10765787 2713.91575549
 2715.92616154 2708.32465134 2713.50045782 2706.37378886 2704.13345928
 2703.60320754 2698.8040278  2682.09677952 2708.19549516 2714.28646692
 2678.89442566 2689.79522301 2701.57443785 2695.07370816 2703.95707863
 2710.342809   2702.51896321 2682.0638571  2712.0800637  2687.24843259
 2695.69288971 2709.39887556 2697.24623105 2695.38599705 2691.36947305
 2705.61879352 2717.7289137  2697.7133568  2721.23236036 2710.99004272
 2707.72644877 2684.05534605 2695.58779897 2712.14835855 2695.47074681
 2702.89741411 2725.68390806 2685.27662102 2720.41216359 2696.32139686
 2724.44383675 2698.77585057 2730.7291049  2704.79742701 2703.11200942
 2703.7454158  2687.8883385  2692.72437893 2690.73167879 2705.84706147
 2725.27426135 2695.28285716 2695.27252179 2694.61047458 2699.33484944
 2707.23227015 2709.93665468 2694.65685835 2721.49336718 2698.92610836
 2694.01818671 2697.51720981 2714.20441761 2697.21478475 2702.38959319
 2697.40290725 2705.58788221 2693.91972097 2710.60679822 2714.21637557
 2697.48651264 2719.20919912 2712.02248651 2701.47345521 2713.94393248
 2688.39743434 2707.97072315 2707.16157973 2712.11113033 2718.29970512
 2705.42869457 2699.91931851 2715.91650036 2694.0286916  2693.47025722
 2688.59833301 2713.87207794 2702.00335108 2709.20626044 2716.01447034
 2702.91864698 2708.22932971 2702.78335909 2687.8413167  2691.87902994
 2706.92250033 2703.25611348 2689.41089108 2705.91896732 2716.05340294
 2695.51917018 2705.29392733 2700.25287645 2711.80682505 2709.36125345
 2697.21399137 2717.54139693 2715.97947241 2698.10392    2717.1698774
 2700.86049239 2715.87355301 2707.6917765  2706.1249752  2707.95380966
 2702.41781196 2695.9100772  2719.1912445  2710.17554546 2709.46509799
 2724.00800406 2696.73617813 2710.54121309 2716.90300397 2712.42639483
 2703.53062776 2719.41836483 2694.56403815 2695.78647778 2697.7998642
 2694.68552733 2712.9902229  2716.64952609 2696.64598707 2719.53775312
 2691.58116332 2699.49879323 2691.80888634 2707.51247501 2680.01472683
 2682.2583737  2706.19081473 2734.42655658 2705.59998779 2698.83359666
 2687.54816445 2701.60442063 2711.0478778  2691.98022188 2699.71738507
 2683.6687696  2713.98438773 2702.43300329 2682.55842784 2691.67699329
 2724.37177744 2720.03906215 2702.02666463 2715.88782344 2696.1409299
 2687.35982829 2720.74813116 2711.48782956 2713.77548996 2711.82368597
 2710.65762098 2715.08091061 2706.32855869 2705.24224823 2693.79933511
 2716.35670433 2700.56482946 2696.09201965 2693.52206364 2706.97913565
 2726.34652844 2703.14866118 2716.43510851 2699.25724461 2713.42725419
 2716.18571934 2693.90465519 2702.81775021 2712.77690407 2692.75879078
 2714.07894326 2711.45332768 2696.95548865 2719.3391007  2730.00466839
 2691.87645608 2714.00142802 2700.71521966 2708.79548812 2679.98342786
 2705.60096983 2703.24641552 2697.72737368 2711.03538122 2684.61998736
 2695.93603604 2722.5598054  2704.34604379 2698.14667588 2712.76901535
 2698.41034715 2710.35645332 2713.49480426 2704.24044704 2690.3909266
 2696.29323171 2692.22343228 2697.41400735 2695.24131806 2698.27024761
 2712.50697777 2720.61338685 2703.92207816 2691.74825688 2699.64029297
 2690.51511716 2687.88123256 2690.86793886 2713.00909629 2712.24643932
 2690.08011507 2695.8226422  2680.69874786 2704.86704631 2678.35235872
 2697.57730663 2681.8985545  2716.8444977  2688.24602052 2724.04896218
 2708.24305725 2700.41402923 2703.71791133 2710.65906973 2703.24293102
 2713.38492258 2726.98486381 2695.62222626 2706.47169859 2716.73094374
 2702.82272653 2714.30762677 2710.42854993 2719.23396205 2718.03823119
 2727.69416155 2697.11377649 2697.16302988 2684.70218444 2688.45013574
 2700.80377274 2693.22822886 2710.89995999 2703.75099504 2695.99083613
 2706.38160466 2699.5363502  2703.51787947 2702.45578048 2713.77353856
 2711.48234517 2717.25134176 2710.52761474 2696.02093907 2702.38551842
 2704.63832095 2699.6625868  2701.53619649 2694.65117597 2724.59959825
 2693.57577308 2714.12791645 2697.89341458 2698.33086013 2699.5396465
 2707.65596022 2713.53218318 2716.65127973 2710.04394269 2704.22539782
 2724.02714926 2701.35165382 2714.31281507 2711.1077048  2705.60976677
 2711.6670134  2710.351968   2718.34876879 2703.50257051 2704.78305834
 2691.27728399 2723.85347517 2725.49048001 2708.91346285 2712.97678146
 2702.52433749 2710.70333981 2698.45703021 2734.5226754  2683.04266329
 2706.15550373 2694.12607478 2703.62235128 2697.88620206 2698.53429154
 2707.49458714 2713.38817704 2704.65685532 2708.40930136 2698.65425954
 2708.28698988 2699.53409491 2698.23874787 2711.71976007 2721.45208638
 2714.98648821 2713.81876873 2692.36263836 2694.22538541 2715.84881232
 2692.90257361 2684.86835722 2710.32053723 2690.43363011 2705.82252781
 2696.28288363 2706.04143718 2686.19047037 2710.2052501  2700.94426418
 2684.58651947 2702.34800087 2700.70982545 2716.53167792 2708.63476641
 2710.75443458 2698.58478301 2694.82268128 2701.69341517 2700.55738795
 2712.53754243 2691.39867911 2694.40021993 2696.41001713 2696.20695148
 2692.95338945 2707.72472795 2693.58260607 2695.80422452 2707.73679762
 2693.61578263 2697.80534817 2698.37698806 2709.99840735 2714.93053944
 2679.90138317 2719.60968049 2710.44990763 2719.32405063 2693.59184825
 2717.31429533 2711.10608721 2701.02899301 2723.06778479 2694.72250245
 2702.34556963 2699.66642716 2710.51965544 2695.54137342 2708.43895102
 2710.81501489 2703.3223363  2711.03706451 2705.2173635  2698.76046193
 2693.67478613 2696.59524781 2695.84109502 2704.36792499 2710.77312707
 2684.45547126 2695.33280989 2701.91591119 2699.0267961  2718.69881962
 2703.72028745 2723.6677602  2704.37530653 2707.14625878 2708.41740882
 2715.63150099 2703.57772553 2707.42413492 2695.7348945  2690.90137243
 2697.0074225  2708.56437596 2711.37017884 2703.21422146 2711.41173183
 2688.50854053 2693.72807152 2718.24040015 2698.9812176  2699.27114424
 2703.6099613  2713.08722146 2704.1268942  2722.85169273 2695.06230762
 2709.87171043 2705.21619937 2704.65117899 2695.51705077 2681.96703168
 2710.9792967  2705.94561346 2706.83197215 2701.52488928 2725.38994176
 2693.94174457 2708.47651165 2688.51593881 2700.21606259 2714.44398665
 2714.3502435  2692.46867559 2718.64571764 2703.535113   2702.02160096
 2715.29876268 2721.82933757 2699.43913147 2687.03173435 2699.88190246
 2715.41080511 2705.69617591 2694.42945325 2697.35998571 2707.03494571
 2713.21407482 2714.1136248  2696.8545382  2697.99144169 2709.83633938
 2685.46464549 2713.81633401 2698.15598976 2687.61997489 2693.97805459
 2693.69921238 2692.19918699 2708.07485306 2705.35889052 2692.71641514
 2697.87814297 2700.22385999 2691.45341246 2697.30798592 2702.59806632
 2689.14073517 2679.45612495 2713.01451309 2688.15659499 2708.91325567
 2694.88774605 2702.84790271 2690.92154118 2701.77875849 2707.66703548
 2701.32215764 2695.31143613 2714.75499706 2687.04631614 2698.35987567
 2695.93319824 2697.47059414 2714.89997232 2719.18293448 2708.39335569
 2710.90269689 2702.49981948 2701.10393177 2699.82229773 2679.0021966
 2705.97828388 2707.21426457 2704.75675973 2699.61750234 2711.93089262
 2705.80338919 2696.95968151 2705.77392253 2709.41030981 2710.57995041
 2692.65911775 2700.12581275 2687.57961096 2708.28080871 2693.81338611
 2684.55029971 2721.71104937 2689.65153171 2707.23525191 2689.40601752
 2708.90602663 2706.43846039 2713.35793065 2695.54435566 2688.7999903
 2693.57865791 2694.8004782  2721.0932468  2706.03802428 2701.44490022
 2701.09755915 2683.8099994  2696.3220184  2718.81844895 2700.94243991
 2695.1151277  2686.22022696 2723.04891623 2704.70831178 2709.26447248
 2714.54519336 2701.35550933 2690.97603174 2718.52933848 2724.50264575
 2706.56842007 2719.12746034 2698.55153141 2681.19759295 2710.66313512
 2697.29846047 2710.1752566  2692.6617914  2703.78225058 2705.73782343
 2707.70109154 2713.88032808 2703.50062842 2716.48754175 2683.23909736
 2710.33462049 2699.89804136 2703.89449001 2718.04963472 2713.95164046]

In [17]:
estimated_profit = pd.DataFrame(new_predictions, columns=['profit'])

In [18]:
new_customers = pd.read_csv('new_customers.csv')

In [19]:
new_customers_with_estimated_profit = pd.concat([new_customers, estimated_profit], axis=1)
new_customers_with_estimated_profit.head()

,customer_id,first_name,last_name,gender,past_3_years_bike_related_purchases,DOB,job_title,job_industry_category,wealth_segment,deceased_indicator,owns_car,tenure,address,postcode,state,country,property_valuation,profit
0,1,Chickie,Brister,Male,86,1957-07-12,General Manager,Manufacturing,Mass Customer,N,Yes,14.0,45 Shopko Center,4500,QLD,Australia,6,2725.516805
1,2,Morly,Genery,Male,69,1970-03-22,Structural Engineer,Property,Mass Customer,N,No,16.0,14 Mccormick Park,2113,NSW,Australia,11,2706.978579
2,3,Ardelis,Forrester,Female,10,1974-08-28,Senior Cost Accountant,Financial Services,Affluent Customer,N,No,10.0,5 Colorado Crossing,3505,VIC,Australia,5,2680.114621
3,4,Lucine,Stutt,Female,64,1979-01-28,Account Representative III,Manufacturing,Affluent Customer,N,Yes,5.0,207 Annamark Plaza,4814,QLD,Australia,1,2709.097066
4,5,Melinda,Hadlee,Female,34,1965-09-21,Financial Analyst,Financial Services,Affluent Customer,N,No,19.0,115 Montana Place,2093,NSW,Australia,9,2693.735839

In [20]:
new_customers_with_estimated_profit.to_csv('new_customers_with_estimated_profit.csv', index=False)

### DONE